add search_analyze endpoint
cloudant-labs/search3-erl pull request #10
Opened 2019-10-04 07:09 UTC by tonysun83

This adds the search_analyze endpoint for search3
```
{"analyzer":"keyword", "text":"ablanks@renovations.com"}

{
    "tokens": [
        "ablanks@renovations.com"
    ]
}
```

2019-10-04 07:17 UTC, rnewson requested changes

2019-10-04 07:17 UTC, rnewson commented on src/search3_httpd.erl
> +        _ when is_list(Analyzer) ->
`List when is_list(List)` is clearer rather than ignore the value.

2019-10-04 07:17 UTC, rnewson commented on src/search3_httpd.erl
> +            throw({bad_request, "analyzer parameter must be a string or an object"})
we'll send this for an empty object which might be confusing.

2019-10-04 07:17 UTC, rnewson commented on src/search3_httpd.erl
> +        _ when is_list(Text) ->
same comment as above, but this shows the danger of this pattern. you're referring to a previously defined variable further up the function, easy to get wrong. Perhaps a few "is_string" and "is_string_or_object" functions could be pulled out for further clarity.

2019-10-04 07:17 UTC, rnewson commented on src/search3_httpd.erl
> +    couch_log:notice("Response ~p", [Response]),
we don't want logs of all of these, do we?

2019-10-04 07:17 UTC, rnewson commented on src/search3_httpd.erl
> +    Response = search3_rpc:analyze(couch_util:to_binary(Analyzer),
do we need to force to binary?

2019-10-04 07:17 UTC, rnewson commented on src/search3_httpd_handlers.erl
> -
?

2019-10-04 15:30 UTC, tonysun83 commented
@rnewson updated per your comments

2019-10-07 14:41 UTC, rnewson approved these changes
+1

2019-10-07 14:44 UTC, merged